### ISSUE TITLE
A CCE in ReplaceExpression strategy

### ISSUE THREAD

**Issue by SeongjoonHong** [kupl/npex#11]
We get a CCE when method `getBlock` is called from a patch template generated from `ReplaceEntireExpression` strategies.
The following is the log from `pdfbox-3572`:
```
ID: ReplaceEntireExpressionLiteral_271-271_1
Before: {
    javax.crypto.Cipher decryptCipher;
    try {
        decryptCipher = javax.crypto.Cipher.getInstance("AES/CBC/PKCS5Padding");
    } catch (java.security.NoSuchAlgorithmException e) {
        // should never happen
        throw new java.lang.RuntimeException(e);
    }
    javax.crypto.SecretKey aesKey = new javax.crypto.spec.SecretKeySpec(finalKey, "AES");
    javax.crypto.spec.IvParameterSpec ips = new javax.crypto.spec.IvParameterSpec(iv);
    decryptCipher.init(decrypt ? javax.crypto.Cipher.DECRYPT_MODE : javax.crypto.Cipher.ENCRYPT_MODE, aesKey, ips);
    byte[] buffer = new byte[256];
    int n;
    while ((n = data.read(buffer)) != (-1)) {
        byte[] dst = decryptCipher.update(buffer, 0, n);
        output.write(dst);
    }
    output.write(decryptCipher.doFinal());
}
PatchBlock type: class spoon.support.reflect.code.CtBlockImpl
Exception in thread "main" java.lang.ClassCastException: spoon.support.reflect.code.CtConditionalImpl cannot be cast to spoon.reflect.code.CtStatement
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtBlock(DefaultJavaPrettyPrinter.java:525)
        at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:57)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:380)
        at spoon.reflect.visitor.ElementPrinterHelper.writeStatement(ElementPrinterHelper.java:170)
        at spoon.reflect.visitor.ElementPrinterHelper.writeIfOrLoopBlock(ElementPrinterHelper.java:452)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtWhile(DefaultJavaPrettyPrinter.java:1951)
        at spoon.support.reflect.code.CtWhileImpl.accept(CtWhileImpl.java:25)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:380)
        at spoon.reflect.visitor.ElementPrinterHelper.writeStatement(ElementPrinterHelper.java:170)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtBlock(DefaultJavaPrettyPrinter.java:528)
        at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:57)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:380)
        at spoon.reflect.visitor.DefaultJavaPrettyPrinter.printElement(DefaultJavaPrettyPrinter.java:266)
        at spoon.support.reflect.declaration.CtElementImpl.toString(CtElementImpl.java:294)
        at java.lang.String.valueOf(String.java:2994)
        at java.io.PrintStream.println(PrintStream.java:821)
        at npex.synthesizer.Main.lambda$main$0(Main.java:129)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at npex.synthesizer.Main.main(Main.java:123)
```

**Comment by SeongjoonHong** [comment]
Resolved.
